import { defineConfig } from 'orval';

export default defineConfig({
  openapi: {
    output: {
      mode: 'single',
      target: './src/apis/autoGenerated/api.ts',
      schemas: './src/apis/autoGenerated/types',
      prettier: true,
    },
    input: {
      target: '../../open-api.json',
    },
  },
});
