/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Nx-Next-Nest
 * Nx-Next-Nest description
 * OpenAPI spec version: 1.0
 */

export * from './createTodoDto';
export * from './updateTodoDto';
